### ISSUE TITLE
Inkplayer Editor Window not displaying content text.

### ISSUE THREAD

**Issue by JarrydHuntley** [inkle/ink-unity-integration#115]
In the latest release (0.9.24) the Inkplayer Editor Window is not displaying content. I tested in Unity 2018.4 and 2019.4. I went back and tested the release on 0.9.3[is the numbering scheme different On the Unity Asset Store?] on the asset store it and worked correctly. 

I'm wondering if something is broken with the text fade in function. 
![image](https://user-images.githubusercontent.com/834187/89108744-ec72e100-d408-11ea-9850-f0c13472ec5c.png)

**Comment by tomkail** [comment]
I'm afraid I can't reproduce this! Have you had any luck chasing it yourself?

**Comment by JacobChrist** [comment]
I'm seeing this same behavior. If you navigate through the game the "Content" section grows as if the font is the same color as the background.

![image](https://user-images.githubusercontent.com/198251/93002686-8c825680-f4ed-11ea-9e6d-1aac351f9483.png)

If I right click on the "blank" box and select copy, then paste, the text is in the copy buffer.

I also have a message saying "Story JSON file has changed. Restart to play updated story." in the Ink Player, yet in the inspector says is says compile successful:

![image](https://user-images.githubusercontent.com/198251/93002702-a328ad80-f4ed-11ea-95a3-ab99169612ab.png)

Suspecting that the dark mode was the issue I change to the personal mode and the issue is the same.  I do see that there is some color difference between output sections that I could not see in dark mode.

![image](https://user-images.githubusercontent.com/198251/93002814-7c1eab80-f4ee-11ea-8904-d433a129f2a0.png)

Unity 2020.1.3f1
Ink Unity Integration 0.9.4

@tomkail where about this is rendered, I can try to see if I can understand what is going on.

**Comment by tomkail** [comment]
@JacobChrist Have a look at DisplayLine in InkPlayerWindow.cs. I did push a fix for animations not working (although the text WAS showing) that won't be in the latest Unity Asset Store version, so I'd recommend updating to latest following the instructions on the 
repo readme first!

**Comment by JacobChrist** [comment]
Just installed 0.9.50 that this problem is resolved for me.
