### ISSUE TITLE
Using ink for NPC dialogue

### ISSUE THREAD

**Issue by Eveliyse** [inkle/ink-unity-integration#26]
Hi there! I recently stumbled upon ink and have already started tinkering with it. I've fallen in love with how easy it is to write with and how smoothly the unity integration went so kudos to you guys!

I have a few questions regarding whether you think ink is a good fit for standard NPC dialogue within a game and if so, do you have any recommendations as to how to go about structuring things.

The way I've gone about it so far is to have a file with many knots, with each knot being it's own 'conversation' that the player can have with a NPC. I've manually copied the knot names into a list and when the player talks to the NPC, the NPC sets any relevant variables (like player name) and picks a random knot name and uses `ChoosePathString("myKnotName")` to play the correct 'conversation'.

It's all working perfectly at the moment but later I want certain knots to only be 'pickable' if certain conditions are met (certain point in the game story, NPC emotions, etc). I was thinking of doing this with tags.

So I guess my questions are:
Are you immediately cringing at how I've gone about implementing my current stuff?
If you didn't immediatly cringe, do you recommend any way to automatically get all the knots in a file?
Do you think using tags to differentiate between knot types is a good idea?

Sorry for the wall of text! Thanks!

**Comment by joningold** [comment]
Hey!

Glad you're enjoying it.

My advice would be to move as much of the logic for picking conversations
into ink; the ink story has access to knowledge about what story content
has been seen so far (that's tedious to reflect back into the game); but
ink can also query the game state using external functions. So I'd always
call one "decider knot" for a character, and then let that knot decide what
content gets used.

But not all games work the same way, of course!

Jon

On Fri, 30 Dec 2016 at 7:54 pm, Sharon <notifications@github.com> wrote:

Hi there! I recently stumbled upon ink and have already started tinkering
with it. I've fallen in love with how easy it is to write with and how
smoothly the unity integration went so kudos to you guys!


I have a few questions regarding whether you think ink is a good fit for
standard NPC dialogue within a game and if so, do you have any
recommendations as to how to go about structuring things.


The way I've gone about it so far is to have a file with many knots, with
each knot being it's own 'conversation' that the player can have with a
NPC. I've manually copied the knot names into a list and when the player
talks to the NPC, the NPC sets any relevant variables (like player name)
and picks a random knot name and uses ChoosePathString("myKnotName") to
play the correct 'conversation'.


It's all working perfectly at the moment but later I want certain knots to
only be 'pickable' if certain conditions are met (certain point in the game
story, NPC emotions, etc). I was thinking of doing this with tags.


So I guess my questions are:


Are you immediately cringing at how I've gone about implementing my current
stuff?


If you didn't immediatly cringe, do you recommend any way to automatically
get all the knots in a file?


Do you think using tags to differentiate between knot types is a good idea?


Sorry for the wall of text! Thanks!




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/inkle/ink-unity-integration/issues/26>, or mute the
thread

**Comment by Eveliyse** [comment]
Wow I would not have thought of doing this in a million years. This seems like the perfect solution for me! Thanks so much! Hope you had a good new year :D
