### ISSUE TITLE
Unity Package Manager support

### ISSUE THREAD

**Issue by tomkail** [inkle/ink-unity-integration#84]
It'd be nice to keep the code out of the way, which I believe is the point of the packages system

**Comment by Feddas** [comment]
Do you mean a Unity Package Manager Package UPM. I know there's a few ways to do this:
1. Reference using a Git URL:
    1. Changing the master branch to have all the package contents, a package.json and *.asmdef at it's root. This is the simplest way for others to refer to the package. But makes maintaining the repo a bit harder. (example: https://github.com/keenanwoodall/Deform/wiki/Installation )
    2. Add a branch that has all the package contents, package.json and *.asmdef at it's root. The branch has to be specified when referencing the package from UPM. (example: https://github.com/dbrizov/NaughtyAttributes/tree/upm )
2. Add the package to some scoped registry, such as https://openupm.com/
3. You can also host your own scoped registry using software like Verdaccio. But that doesn't seem too useful for this project.

**Comment by tomkail** [comment]
Oh thanks for this! That’s exactly what I’m looking for, you’ve saved me
from an afternoon of googling. Setting up a branch feels a lesser evil, ill
sort it when  I next get done free time!
Ta!

**Comment by klootas** [comment]
Yes, a "upm" branch would be crazy appreciated!

I would love to use ink in my game but the compilation time of my project literally doubled after downloading the unity plugin...

**Comment by tomkail** [comment]
Would a UPM fix that? I’d be happy for someone to look at making an ASMDEF
to improve compile tiles!

**Comment by joethephish** [comment]
We already have an asmdef (https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/InkLibs/Ink-Libraries.asmdef) though I’m an advocate of removing it since it’s useful to be able to hack into internal-defined stuff when you want to. (Despite me being the one who made it all internal!)

Though I guess you mean an asmdef for the whole package? I suppose as soon as it’s a package we would no longer even have the option of using internal defined stuff.... but maybe the argument should be that only people who wanted to do more advanced ink integration should build ink code directly into their project rather than keeping it in an external package....

Or, I guess maybe I should just be liberally opening up stuff that’s currently defined as internal....!

**Comment by klootas** [comment]
I had very little luck with asmdef-files. Visual Studio understands them in design time, but the compilation time for the project is more or less unaffected. I haven't seen UPM packages affect compilation times so far (but hey - when it come's to Unity's compilation model pretty much anything can happen).

The 100% safe way is to just drop a precompiled dll in the assets folder. But this doesn't always work depending on how files are referenced in design time (editor). Anyone this with this plugin?

**Comment by klootas** [comment]
To be more specific about asmdef files - they work if you port your entire project to support that model - but only in the editor. That is, let's say you have everything as asmdef projects. Compilations in your editor will now appear to be really fast, but as soon as you switch over to Unity you notice that it's still rebuilding everything from scratch...

So in practice the only way I find that really works is precompiling a dll (and possibly UPM packages). Has anyone tried either with this plugin?

**Comment by danielheim** [comment]
I have been able to configure Ink as an "[embedded package](https://docs.unity3d.com/Manual/CustomPackages.html#EmbedMe)", relatively easily.

After downloading extracting the latest release, I moved the `Assets/Plugins/Ink` folder to `Packages/Ink` and wrote a simple `package.json` as follows:
```
{
	"name": "com.inkle.ink",
	"displayName": "Ink",
	"version": "0.9.4"
}
```
Unity now treats the library as if I installed it via the Package Manager.

Adding to previous [discussions](#issuecomment-595615690), I would suggest a new repository which only contains the library codebase and `package.json` at the root level. You can then provide that as dependancy of the sample project in this repository.
You'll probably also need to restructure the codebase as per Unity's [conventions](https://docs.unity3d.com/Manual/cus-layout.html).

**Comment by tomkail** [comment]
That's brilliant, thanks for looking into this! I'm not sure how I feel about having the bulk of the project in another repo though. What does everyone else think?

**Comment by danielheim** [comment]
> I'm not sure how I feel about having the bulk of the project in another repo though.

That's only if you'd like to keep this repo as a self contained unity project.

**Comment by klootas** [comment]
> I have been able to configure Ink as an "[embedded package](https://docs.unity3d.com/Manual/CustomPackages.html#EmbedMe)", relatively easily.
> 
> After downloading extracting the latest release, I moved the `Assets/Plugins/Ink` folder to `Packages/Ink` and wrote a simple `package.json` as follows:
> 
> ```
> {
> 	"name": "com.inkle.ink",
> 	"displayName": "Ink",
> 	"version": "0.9.4"
> }
> ```
> 
> Unity now treats the library as if I installed it via the Package Manager.
> 
> Adding to previous [discussions](#issuecomment-595615690), I would suggest a new repository which only contains the library codebase and `package.json` at the root level. You can then provide that as dependancy of the sample project in this repository.
> You'll probably also need to restructure the codebase as per Unity's [conventions](https://docs.unity3d.com/Manual/cus-layout.html).

Much appreciated!
Note that if you also need to access any (public) types in the Ink.UnityIntegration namespace, you also need to add an .asmdef-file in the root ink-folder:
{
    "name": "Ink.UnityIntegration",
    "references": ["Ink-Libraries"],
    "includePlatforms": [],
    "excludePlatforms": []
}

**Comment by tomkail** [comment]
Have you managed to get the asmdef working? Last time I tried it led to a bazillion errors and I gave up!

**Comment by tomkail** [comment]
Nice! I'll give this a go later :)

**Comment by danielheim** [comment]
I've just noticed the custom editors stop working after moving the package. Did anyone else have this issue?

**Comment by tomkail** [comment]
I believe that you need a separate asmdef for editor stuff - this was the
nightmarish mess of code I ran into when I last tried this and gave up! Do
let me know if you work it out though, I'd really love to make this happen!

**Comment by klootas** [comment]
> I've just noticed the custom editors stop working after moving the package. Did anyone else have this issue?

Did you try to create the .asmdef I described above? I think that should do it!

**Comment by danielheim** [comment]
> Did you try to create the .asmdef I described above? I think that should do it!
Yes, I did. I named it `Ink.UnityIntegration.asmdef` and saved the JSON as per your post. Still having issues.

**Comment by klootas** [comment]
Odd, though I'm not really sure what you mean by "custom editors" so maybe I have yet to experience this error :)

Anyway, here's a zipped version of my whole ink-folder if you want to compare:
https://1drv.ms/u/s!Amz_vh8OYDX3vL5sPA7j4i5TUihKHA?e=gnRdjg

**Comment by danielheim** [comment]
> Anyway, here's a zipped version of my whole ink-folder if you want to compare:

Thanks, I'll check it out later

**Comment by danielheim** [comment]
Thanks again @klootas,
I tried your zip file, but I'm still getting the Warnings. And I can't see the Custom Editors, i.e. the DefaultAssetEditor isn't displaying in the Inspector window when I select my Ink file in Unity.

I tried importing in to a new (clean) project, but then I get a lot of errors. I'm using Unity 2020.1.4f1.

I might stick to the old approach for now. Thanks anyway.

**Comment by rhys-vdw** [comment]
Hey there, I was going to tackle this one this weekend but I see the discussion has moved on since I last checked in.

Re: repos I would agree that you should have two repos. `unity-ink-integration` which is just the package to be installed as as a dependency, and `unity-ink-integration-example` which is a standalone example of using the ink package (with the other repo as its dependency). I would suggest forking this repo into the other so that the history of each codebase is retained.

FWIW I've got the ink integration full configured with `asmdef`s in our game. As of last update it looks like this:

```
Ink/Ink.asmdef
Ink/Tools/Player Window/Editor/Ink_PlayerWindow_Editor.asmdef
Ink/Tools/Build Validation/Editor/Ink_Tools_BuildValidation_Editor.asmdef
Ink/Tools/Ink Inspector/Editor/Ink_Tools_InkInspector_Editor.asmdef
Ink/Core/Editor/Ink_Core_Editor.asmdef
Ink/Example/Scripts/Editor/Ink_Example_Editor.asmdef
Ink/InkLibs/Ink-Libraries.asmdef
```

**Comment by klootas** [comment]
Interesting, I would suggest opting for a solution that works for both the Asset and the Package approach (I see Spine do this for their Unity runtime asset/package - drop it in Assets and the package.json is ignored or drop it in Packages if you don't want to recompile it every time you compile your code.

BTW: Now that you have separate .asmdef for editor stuff, does this fixes the problems raised by @danielheim?

**Comment by rhys-vdw** [comment]
> I believe that you need a separate asmdef for editor stuff - this was the nightmarish mess of code I ran into when I last tried this and gave up!
— @tomkail 

That's right, you need one (or more) assembly for each chunk of editor functionality. Either an asmdef for each `Editor` folder (if following the old pattern), as an "assembly reference" in additional folders to combine them all into the same editor asembly. You just need to think of a dependency tree where each assembly is given a reference to other code that it relies on. e.g. 

![image](https://user-images.githubusercontent.com/822105/92345066-6df61700-f10b-11ea-97db-4fcdf27ffe1e.png)

> Now that you have separate .asmdef for editor stuff, does this fixes the problems raised by @danielheim?
— @klootas 

Not sure, if the editor stuff is included in the main assembly then you'll find that the project doesn't build because `UnityEditor` dependency is not available at build time. I haven't found that editor becomes unsupported in build assemblies, but maybe it does. Either way there is no issue in our project, everything works fine.

>  Interesting, I would suggest opting for a solution that works for both the Asset and the Package approach. I've seen Spine do this for their Unity runtime asset/package - drop it in Assets and the package.json is ignored or drop it in Packages if you don't want to recompile it every time you compile your code.
@klootas 

Thanks for this. I had a look—you can see how it works [here](http://esotericsoftware.com/spine-unity#Optional--Extension-UPM-Packages). The problem with their approach, as you hinted at, is that it requires you to manually copy the package into your `Packages` folder, which _should_ be managed by UPM. The goal of UPM support (as far as I'm concerned) is to remove dependencies from version control.

UPM can handle packages that are either:
- Published to a package registry (such as https://openupm.com/) or,
- Hosted in a git repo with a `package.json` at its root folder ([as my other project does](https://github.com/rhys-vdw/unity-destringer#install)).

In the interests of making as few changes as possible and retaining current build and release processes, I will make turn the nested `Assets/Plugins/Ink` folder into a UPM package.

**This means that the project must be released on a third party package server (such as OpenUPM) to be depended on by client projects**

The other option would be to split the project into two repositories as I [previously suggested](https://github.com/inkle/ink-unity-integration/issues/84#issuecomment-687696733).

For @tomkail the main change to release will be the need to bump the `version` in the `package.json` each time you want to release. Hopefully we can simply add this to your release script. I believe that OpenUPM automatically scans all its package repos and updates references when it sees a change in this field.

**Comment by danielheim** [comment]
Just installed the package via openupm. Thanks for your efforts @rhys-vdw and team!

**Comment by klootas** [comment]
Works great - thanks a bunch! 👊

**Comment by tomkail** [comment]
Yeah big thanks to everyone here, and @rhys-vdw for doing the heavy lifting!
