### ISSUE TITLE
Ink Inspector broken in Unity 2019

### ISSUE THREAD

**Issue by tomkail** [inkle/ink-unity-integration#92]
DefaultAssetEditor's OnInspectorGUI seems not to fire, although OnHeaderGUI does.
Not sure why. Potentially it's being overridden in some new Unity code else?

**Comment by onefifth** [comment]
I can confirm this is fixed in Unity 2019.3.0f1 and the manual call to `OnInspectorGUI();` from inside `InkInspector.OnHeaderGUI()` is no longer needed.
Based on the status of [this bug](https://issuetracker.unity3d.com/issues/overridden-oninspectorgui-method-is-not-called-when-using-customeditor-typeof-defaultasset) it might be fixed for all versions?

**Comment by tomkail** [comment]
Ah good find! I’ll leave it for now since it does no harm, and kill it
sometime in the future when we’re reliably all on other versions of Unity
